plink_bfile: /scratch/scjp_root/scjp0/ccrober/proj-t1d-u01-genotypes/merge_nih_alberta/results/merged
donor_meta_data: /scratch/scjp_root/scjp0/ccrober/proj-t1d-u01-genotypes/genotype_qc/data/donor_meta_data_2024-04-19.txt
batch_table: /scratch/scjp_root/scjp0/ccrober/proj-t1d-u01-genotypes/genotype_qc/data/genotype_batch_table.txt
