__default__:
  mem: "10G"
  cpus: "1"
  ntasks: "1"
  name: "JOBNAME.{rule}.{wildcards}"
  output: "logs/smk.{rule}.{wildcards}.out"
  time: "24:00:00"
  partition: "standard"
  account: "your_account_name"


align:
  mem: "60G"
